bootleg/urls.py
from bootleg.views.system_views import DeployInfoView, SystemInfoView, ModelsInfoView, DebugView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.utils.translation import ugettext as _
from django.views.generic import RedirectView

import bootleg
from bootleg.conf import bootleg_settings
from bootleg.forms.auth_forms import LoginForm
from bootleg.views.auth_views import CustomLoginView, LogoutView, change_password, \
    CustomPasswordResetView, PasswordResetBaseView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView
from bootleg.views.generic_model_views import GenericListView, GenericModelCreateView, GenericModelUpdateView, \
    GenericModelCloneView, GenericModelDetailView, GenericModelDeleteView
from bootleg.views.json_views import JSONAutocompleteView, JSONFieldAutocompleteView
from bootleg.views.views import DevNullView, CrashView, ErrorTestView, CreatedView, DjangoQLHelpView, ErrorView
from bootleg.views.ajax_views import JavascriptErrorView

# setup, indeed
bootleg.setup()

app_name = "bootleg"

urlpatterns = [
    #######################################
    # basic URLs
    #######################################
    # a test URL, to test if the site is working. More or less...
    path("dev-null/", DevNullView.as_view(), name="dev_null"),

    #######################################
    # auth/login
    #######################################
    path("login/", CustomLoginView.as_view(authentication_form=LoginForm, page_title=_("Login")), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    # password
    path("password/", change_password, name="change_password"),
    path("password/reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path("password/reset/done/", PasswordResetBaseView.as_view(extra_text="Instructions on how to reset the password "
                                                                          "has been sent to your email-address."),
         name="password_reset_done"),
    path("password/reset/<uidb64>/<token>/", CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password/reset/complete/", CustomPasswordResetCompleteView.as_view(),
         name="password_reset_complete"),

    #######################################
    # list view(s)
    #######################################
    path("list/<model_name>/", GenericListView.as_view(), name="list_view"),

    #######################################
    # generic models
    #######################################
    path("create/<model_name>/", GenericModelCreateView.as_view(), name="create_model"),
    path("update/<model_name>/<int:pk>", GenericModelUpdateView.as_view(), name="update_model"),
    path("view/<model_name>/<int:pk>", GenericModelDetailView.as_view(), name="model_detail"),
    path("clone/<model_name>/<int:pk>", GenericModelCloneView.as_view(), name="clone_model"),
    path("delete/<model_name>/<int:pk>", GenericModelDeleteView.as_view(), name="delete_model"),

    #######################################
    # created page
    #######################################
    path("created/<model_name>", CreatedView.as_view(), name="created"),

    #######################################
    # hxr-views
    #######################################
    path("json/<model_name>/", JSONAutocompleteView.as_view(), name="json_autocomplete"),
    path("json/<model_name>/<field_name>", JSONFieldAutocompleteView.as_view(), name="json_field_autocomplete"),
    path("ajax/javascript-error/", JavascriptErrorView.as_view(), name="javascript_error"),

    #######################################
    # misc-ish
    #######################################
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url(bootleg_settings.FAVICON_FILE))),

    #######################################
    # djangoql syntax help
    #######################################
    path("djangoql/", DjangoQLHelpView.as_view(page_title=_("DjangoQL")), name="djangoql_help"),

    #######################################
    # deploy/system/debug info
    #######################################
    path("deploy/info/", DeployInfoView.as_view(), name="deploy_info"),
    path("system/info/", SystemInfoView.as_view(), name="system_info"),
    path("system/debug/", DebugView.as_view(), name="debug"),

    #######################################
    # errors
    #######################################
    path("error/", ErrorView.as_view(), name="general_error"),

    #######################################
    # error page test
    #######################################
    path("obscurity-by-test/error/<error_code>/", ErrorTestView.as_view(), name="error_test"),

    #######################################
    # elastic search info
    #######################################
    path("models/info/", ModelsInfoView.as_view(), name="models_info"),

    #######################################
    # crash-url - to test errors
    #######################################
    path("crash/", CrashView.as_view(), name="crash"),

]

if settings.DEBUG:
    media_url = getattr(settings, "MEDIA_URL", None)
    media_root = getattr(settings, "MEDIA_ROOT", None)
    # add media ... if it's debug and we have settings
    if media_url and media_root:
        urlpatterns += static(media_url, document_root=media_root)

bootleg/templates/bootleg/includes/css.html
{% load compress static %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css">
{% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootleg/css/bootleg.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootleg/css/vendor/easy-autocomplete.css' %}" />
    {% for css_file in bootleg_settings.CSS_FILES %}
        <link rel="stylesheet" type="text/css" href="{% static css_file %}" />
    {% endfor %}
    {% for css_file in bootleg_settings.EXTRA_CSS_FILES %}
        <link rel="stylesheet" type="text/css" href="{% static css_file %}" />
    {% endfor %}
    {% if view.extra_css %}
        {% for css_file in view.extra_css %}
            <link rel="stylesheet" type="text/css" href="{% static css_file %}" />
        {% endfor %}
    {% endif %}
{% endcompress %}

bootleg/templates/bootleg/includes/deploy_info.html
{% load i18n humanize bootleg bootstrap_tags %}
{% block content %}

<h3>{{ git_data.parsed_git_url.repo }} - {% trans "git/repo" %}</h3>

<p class="mb-4"><a href="{{ view.git_data.github_url }}">{{ view.git_data.github_url }}</a>

<table class="{% get_default_table_classes %}">
<tbody>
    {% if repo.description %}
        <tr>
            <td>{% trans "Description" %}</td>
            <td>{{ repo.description }}</td>
        </tr>
    {% endif %}
    <tr>
        <td>{% trans "Active branch" %}</td>
        <td>{{ view.git_data.repo.active_branch }}</td>
    </tr>
    <tr>
        <td>{% trans "Branches" %}</td>
        <td>
            {% for branch in view.git_data.repo.branches %}
                {{ branch }} {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </td>
    </tr>
   <tr>
        <td>{% trans "git dir" %}</td>
        <td>{{ view.git_data.repo.git_dir }}</td>
    </tr>
</tbody>
</table>

<h3>{% trans "Latest commits" %}</h3>
<table class="{% get_default_table_classes %}">
<tbody>
    <tr>
        <th>{% trans "Date" %}</th>
        <th>{% trans "Author" %}</th>
        <th>{% trans "Message" %}</th>
        <th>{% trans "Type" %}</th>
        <th></th>
    </tr>
    {% for commit in view.git_data.repo.iter_commits %}
        {% if view.git_data.repo.head.object == commit %}
            <tr class="table-success">
        {% else %}
            <tr>
        {% endif %}
        <td>{{ commit.committed_datetime }} <small>({{ commit.committed_datetime|naturaltime }})</small></td>
            <td>{{ commit.author }}</td>
            <td>{{ commit.message }}</td>
            {% if repo.head.object == commit %}
                    <td>{% trans "Current commit" %}</td>
            {% else %}
                    <td>{{ commit.type }}</td>
            {% endif %}
        <td><a href="{{ github_url }}/commit/{{ commit }}">{% trans "github" %}</a></td>
            </tr>
    {% endfor %}
</tbody>
</table>
{% endblock %}

bootleg/templates/bootleg/includes/deploy_status.html
{% extends "bootleg/base.html" %}
{% load static i18n bootleg bootstrap_tags %}
{% block content %}

<h3>{{ parsed_url.repo }} - {% trans "git/repo" %}</h3>

<p class="mb-4"><a href="{{ github_url }}">{{ github_url }}</a>

<table class="{% get_default_table_classes %}">
<tbody>
    <tr>
        <td>{% trans "Description" %}</td>
        <td>{{ repo.description }}</td>
    </tr>
    <tr>
        <td>{% trans "Active branch" %}</td>
        <td>{{ repo.active_branch }}</td>
    </tr>
    <tr>
        <td>{% trans "Branches" %}</td>
        <td>
            {% for branch in repo.branches %}
                {{ branch }} {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </td>
    </tr>
   <tr>
        <td>{% trans "git dir" %}</td>
        <td>{{ repo.git_dir }}</td>
    </tr>
</tbody>
</table>

<h3>{% trans "Latest commits" %}</h3>
<table class="{% get_default_table_classes %}">
<tbody>
    <tr>
        <th>{% trans "Date" %}</th>
        <th>{% trans "Author" %}</th>
        <th>{% trans "Message" %}</th>
        <th>{% trans "Type" %}</th>
        <th></th>
    </tr>
    {% for commit in repo.iter_commits %}
        {% if repo.head.object == commit %}
            <tr class="table-success">
        {% else %}
            <tr>
        {% endif %}
            <td>{{ commit.committed_datetime }}</td>
            <td>{{ commit.author }}</td>
            <td>{{ commit.message }}</td>
            {% if repo.head.object == commit %}
                    <td>{% trans "Current commit" %}</td>
            {% else %}
                    <td>{{ commit.type }}</td>
            {% endif %}
        <td><a href="{{ github_url }}/commit/{{ commit }}">{% trans "github" %}</a></td>
            </tr>
    {% endfor %}
</tbody>
</table>
{% endblock %}

bootleg/templates/bootleg/includes/form.html
{% load i18n crispy_forms_tags bootstrap_tags bootleg %}
{% debug_bl "-> bootleg/form.html" %}

{% setvar "a string" as new_template_var %}

{% if not view.right_template %}
    {% setvar " w-50" as form_help_class %}
{% endif %}

{% if form.is_search_form %}
    <form id="bootleg_q_form">
        <div class="input-group{{ form_help_class }}">
            {{ form.q }}
            {% render_search_append %}
        </div>
    </form>
    {% if dql_form %}
        <p class="mt-2">
            <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse"
                    data-target="#dql_search" aria-expanded="false" aria-controls="dql_search">
            {% trans "Advanced search" %}
            </button>
        </p>
        <div class="collapse {% if request.GET.dql %}show{% endif %}" id="dql_search">
            <form id="bootleg_dql_form">
                <div class="input-group{{ form_help_class }} mt-3">
                    {{ dql_form.dql }}
                    {% render_search_append %}
                </div>
            </form>
        </div>
    {% endif %}
{% else %}
    {% if forms or form %}
        {% if bootleg_settings.WRAP_FORMS %}
            <div class="{{ form_help_class }} bg-light border rounded p-4">
        {% else %}
            <div class="{{ form_help_class }}">
        {% endif %}
    {% endif %}
{% endif %}

{% if forms %}
    {# TODO: don't always use multipart #}
    <form method="post" action="" enctype="multipart/form-data">
        {% crispy form helper %}
        {% for inner_form in forms %}
            <h5 class="mb-3 mt-3">{{ inner_form.heading }}</h5>
            {% crispy inner_form helper %}
        {% endfor %}
        <input type="submit" name="submit" value="{{ view.submit_button_text }}" class="btn btn-primary loading-button" id="submit-id-submit">
    </form>
{% else %}
    {% if form and not form.is_search_form %}
        {% if view.form_template %}
            {% include view.form_template %}
        {% else %}
            {% if form.helper %}
                {% crispy form form.helper %}
            {% else %}
                {% crispy form %}
            {% endif %}
        {% endif %}
    {% endif %}
{% endif %}

{% if forms or form and not form.is_search_form %}
    </div>
{% endif %}

bootleg/templates/bootleg/includes/js.html
{% load compress static %}
<script>
    var Context = {
        jsErrorURL: "{% url 'bootleg:javascript_error' %}",
        dateFormat: "{{ bootleg_settings.JS_DATE_FORMAT }}",
        dateTimeFormat: "{{ bootleg_settings.JS_DATETIME_FORMAT }}",
        {% if bootleg_settings.SPINNER_CSS_CLASS %}
            spinnerClass: "{{ bootleg_settings.SPINNER_CSS_CLASS }}",
        {% endif %}
        autoCompleteLimit: "{{ bootleg_settings.AUTOCOMPLETE_LIMIT }}"
    }
    var Text = {
        unknownError: "Unknown error",
        urlNotFound: "Requested URL not found",
        internalServerError: "Internal Server Error",
        reference: "Reference",
        jsonParseError: "Failed parsing JSON",
        requestTimeout: "The request timed out",
    }
</script>

{% if not bootleg_settings.EXCLUDE_JQUERY is True %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
{% endif %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"></script>
<script src="https://kit.fontawesome.com/28738b72bb.js" crossorigin="anonymous"></script>
{% compress js %}
    <script src="{% static 'bootleg/js/vendor/jquery.easy-autocomplete.js' %}"></script>
    <script src="{% static 'bootleg/js/vendor/jquery.highlight-5.patched.js' %}"></script>
    <script src="{% static 'bootleg/js/vendor/spin.min.js' %}"></script>
    <script src="{% static 'bootleg/js/bootleg.js' %}"></script>
{% endcompress %}

{% for js_file in bootleg_settings.JS_FILES %}
    <script src="{% static js_file %}"></script>
{% endfor %}

{% if bootleg_settings.JS_TEMPLATE %}
    {% include bootleg_settings.JS_TEMPLATE %}
{% endif %}

bootleg/templates/bootleg/includes/messages.html
{% load bootstrap_tags %}
<div id="main_error" class="hidden mb-4 mt-4">
    {% get_alert "danger" "[e]" True %}
</div>
{% if messages %}
    <div class="mb-4 mt-4">
        {% for message in messages %}
            {% get_alert message.tags message %}
        {% endfor %}
    </div>
{% endif %}