bootleg/urls.py
from bootleg.views.system_views import DeployInfoView, SystemInfoView, ModelsInfoView, DebugView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.utils.translation import ugettext as _
from django.views.generic import RedirectView

import bootleg
from bootleg.conf import bootleg_settings
from bootleg.forms.auth_forms import LoginForm
from bootleg.views.auth_views import CustomLoginView, LogoutView, change_password, \
    CustomPasswordResetView, PasswordResetBaseView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView
from bootleg.views.generic_model_views import GenericListView, GenericModelCreateView, GenericModelUpdateView, \
    GenericModelCloneView, GenericModelDetailView, GenericModelDeleteView
from bootleg.views.json_views import JSONAutocompleteView, JSONFieldAutocompleteView
from bootleg.views.views import DevNullView, CrashView, ErrorTestView, CreatedView, DjangoQLHelpView, ErrorView
from bootleg.views.ajax_views import JavascriptErrorView

# setup, indeed
bootleg.setup()

app_name = "bootleg"

urlpatterns = [
    #######################################
    # basic URLs
    #######################################
    # a test URL, to test if the site is working. More or less...
    path("dev-null/", DevNullView.as_view(), name="dev_null"),

    #######################################
    # auth/login
    #######################################
    path("login/", CustomLoginView.as_view(authentication_form=LoginForm, page_title=_("Login")), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    # password
    path("password/", change_password, name="change_password"),
    path("password/reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path("password/reset/done/", PasswordResetBaseView.as_view(extra_text="Instructions on how to reset the password "
                                                                          "has been sent to your email-address."),
         name="password_reset_done"),
    path("password/reset/<uidb64>/<token>/", CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password/reset/complete/", CustomPasswordResetCompleteView.as_view(),
         name="password_reset_complete"),

    #######################################
    # list view(s)
    #######################################
    path("list/<model_name>/", GenericListView.as_view(), name="list_view"),

    #######################################
    # generic models
    #######################################
    path("create/<model_name>/", GenericModelCreateView.as_view(), name="create_model"),
    path("update/<model_name>/<int:pk>", GenericModelUpdateView.as_view(), name="update_model"),
    path("view/<model_name>/<int:pk>", GenericModelDetailView.as_view(), name="model_detail"),
    path("clone/<model_name>/<int:pk>", GenericModelCloneView.as_view(), name="clone_model"),
    path("delete/<model_name>/<int:pk>", GenericModelDeleteView.as_view(), name="delete_model"),

    #######################################
    # created page
    #######################################
    path("created/<model_name>", CreatedView.as_view(), name="created"),

    #######################################
    # hxr-views
    #######################################
    path("json/<model_name>/", JSONAutocompleteView.as_view(), name="json_autocomplete"),
    path("json/<model_name>/<field_name>", JSONFieldAutocompleteView.as_view(), name="json_field_autocomplete"),
    path("ajax/javascript-error/", JavascriptErrorView.as_view(), name="javascript_error"),

    #######################################
    # misc-ish
    #######################################
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url(bootleg_settings.FAVICON_FILE))),

    #######################################
    # djangoql syntax help
    #######################################
    path("djangoql/", DjangoQLHelpView.as_view(page_title=_("DjangoQL")), name="djangoql_help"),

    #######################################
    # deploy/system/debug info
    #######################################
    path("deploy/info/", DeployInfoView.as_view(), name="deploy_info"),
    path("system/info/", SystemInfoView.as_view(), name="system_info"),
    path("system/debug/", DebugView.as_view(), name="debug"),

    #######################################
    # errors
    #######################################
    path("error/", ErrorView.as_view(), name="general_error"),

    #######################################
    # error page test
    #######################################
    path("obscurity-by-test/error/<error_code>/", ErrorTestView.as_view(), name="error_test"),

    #######################################
    # elastic search info
    #######################################
    path("models/info/", ModelsInfoView.as_view(), name="models_info"),

    #######################################
    # crash-url - to test errors
    #######################################
    path("crash/", CrashView.as_view(), name="crash"),

]

if settings.DEBUG:
    media_url = getattr(settings, "MEDIA_URL", None)
    media_root = getattr(settings, "MEDIA_ROOT", None)
    # add media ... if it's debug and we have settings
    if media_url and media_root:
        urlpatterns += static(media_url, document_root=media_root)

bootleg/forms/base.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import Form, ModelForm, BaseForm

from bootleg.logging import logging
from django.utils.translation import ugettext as _

METHOD_GET = "GET"


def get_default_form_helper(submit_text, inline=False, method="POST", css_class=None):
    clazz = "btn-primary"
    if css_class:
        clazz = css_class
    helper = FormHelper()
    helper.add_input(Submit('submit', submit_text, css_class="loading-button %s" % clazz))
    helper.form_id = "bootleg_form"
    helper.form_method = method
    if inline:
        helper.form_class = 'form-inline'
    return helper


def log_form_errors(form):
    if form.errors:
        BaseForm.logger.warning("[%s] Errors: [%s] " % (form.__class__.__name__, form.errors.as_data()))


# some dirty monkey patching to log form errors
def monkey_patched_is_valid(self):
    log_form_errors(self)
    return self.is_bound and not self.errors


# set this monkey patched method on Django's BaseForm
BaseForm.is_valid = monkey_patched_is_valid


class BaseForm(Form):
    inline = False
    method = "POST"
    logger = logging.get_logger("forms", "bootleg.forms")
    submit_text = _("Submit")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = get_default_form_helper(self.submit_text, self.inline, self.method)

    def has_submitted_value(self, request):
        for field in self.fields:
            if self.method == "POST":
                if request.POST.get(field):
                    return True
            if self.method == "GET":
                if request.GET.get(field):
                    return True

        return False

    def add_attribute(self, field, key, value):
        field.widget.attrs.update({key: value})

    def add_class(self, field, klass):
        if "class" not in field.widget.attrs:
            field.widget.attrs["class"] = klass
        else:
            field.widget.attrs["class"] += " " + klass

    def is_search_form(self):
        if len(self.fields) == 1 and "q" in self.fields:
            return True
        return False


class BaseModelForm(ModelForm, BaseForm):
    submit_text = _("Save")
    pass

bootleg/views/base.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView, TemplateView, FormView, DetailView

from bootleg.conf import bootleg_settings
from bootleg.forms.base import get_default_form_helper


class StaffRequiredView:

    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class SuperUserRequiredView:

    @user_passes_test(lambda u: u.is_superuser)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class BaseView:
    template_name = bootleg_settings.BASE_TEMPLATE
    page_title = None
    heading = None
    extra_text = None


class BaseTemplateView(BaseView, TemplateView):

    def get_extra_text(self):
        return self.extra_text


class BaseFormView(BaseTemplateView, FormView):
    pass


class BaseDetailView(BaseView, DetailView):
    pass


class StaffRequiredTemplateView(StaffRequiredView, BaseTemplateView):
    pass


class SuperuserRequiredTemplateView(StaffRequiredView, BaseTemplateView):
    pass


class BaseCreateUpdateView(BaseView):
    template_name = bootleg_settings.BASE_TEMPLATE
    success_url = reverse_lazy("bootleg:index")

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.helper = get_default_form_helper(self.submit_button_text)
        return form


class BaseCreateView(BaseCreateUpdateView, CreateView):
    model = None
    submit_button_text = _("Save")

    def get_success_url(self):
        # is this the right way to do it? with __name__.lower?
        return reverse("bootleg:created", args=[self.object._meta.model.__name__.lower()])

    def form_valid(self, form):
        message = _("The %s was added" % self.model._meta.verbose_name)
        messages.add_message(self.request, messages.INFO, message)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not hasattr(self, "heading") or self.heading is None:
            context["heading"] = _("Create %s" % self.model._meta.verbose_name)
        if not hasattr(self, "page_title") or self.page_title is None:
            context["page_title"] = _("Create %s" % self.model._meta.verbose_name)
        return context


class BaseUpdateView(BaseCreateUpdateView, UpdateView):
    model = None
    submit_button_text = _("Update")

    def form_valid(self, form):
        message = _("The %s was updated" % self.model._meta.verbose_name)
        messages.add_message(self.request, messages.INFO, message)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not hasattr(self, "heading") or self.heading is None:
            context["heading"] = _("Update %s" % self.model._meta.verbose_name)
        if not hasattr(self, "page_title") or self.page_title is None:
            context["page_title"] = _("Update %s" % self.model._meta.verbose_name)
        return context


class CSRFExemptView(View):

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class FormWithRequestMixin(View):

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

bootleg/templates/bootleg/base.html
{% load static i18n bootleg bootstrap_tags compress %}
{% if not request.is_ajax %}
<!doctype html>
<html lang="{{ bootleg_settings.html_language_code }}">
<head>
<meta charset="utf-8">
<title>{% block page_title %}{% get_page_title model view.page_title page_title %}{% endblock %}</title>
<meta name="description" content="{% block meta_description %}{% get_first_with_value meta_description view.meta_description view.title %}{% endblock %}" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="shortcut icon" type="image/x-icon" href="{% static bootleg_settings.FAVICON_FILE %}" />
{% include "bootleg/includes/css.html" %}
{% block extra_head %}
{% endblock %}

{# google analytics :( #}
{% if bootleg_settings.google_analytics_account %}
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ bootleg_settings.google_analytics_account }}"></script>
    <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '{{ bootleg_settings.google_analytics_account }}');
    </script>
{% endif %}
{% if bootleg_settings.HEAD_TEMPLATE %}
    {% include bootleg_settings.HEAD_TEMPLATE %}
{% endif %}
</head>

<body>
{% include bootleg_settings.NAVIGATION_TEMPLATE %}

<main role="main" id="main" class="{{ bootleg_settings.CONTAINER_CSS_CLASS }}">
<h1>
{% block h1 %}
    {% get_first_with_value heading view.heading page_title view.page_title %}
{% endblock %}
</h1>
{% endif %}

{% include "bootleg/includes/messages.html" %}

{% block content %}
    {% debug_bl "-> bootleg/base.html" %}
    {% if view.right_template %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-6">
                    {% if view.extra_template %}
                        {% include view.extra_template %}
                    {% endif %}
    {% endif %}
    {% if view.page_text %}
        {{ view.page_text }}
    {% endif %}
    {% if not model.meta.wide_table %}
        {% include "bootleg/includes/form.html" %}
    {% endif %}
    {% if view.get_extra_text %}
        {{ view.get_extra_text|safe }}
    {% endif %}
    {% if extra_text %}
        {{ extra_text|safe }}
    {% endif %}
    {% if view.right_template %}
            </div>
            <div class="col-6">
                {% include view.right_template %}
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block page_content %}
{% endblock %}

{% if not request.is_ajax %}

{% block footer %}
{% endblock %}
</main>

{% if bootleg_settings.FOOT_TEMPLATE %}
    {% include bootleg_settings.FOOT_TEMPLATE %}
{% endif %}

{% include "bootleg/includes/js.html" %}
{% block extra_body %}
{% endblock %}
{% if bootleg_settings.BOOTLEG_DISCRETE_DEBUG and request.user.is_staff %}
    <div class="text-muted text-center">
        <small>⌒°(❛ᴗ❛)°⌒ {{ bootleg_settings.SITE_NAME }}  ⌒°(❛ᴗ❛)°⌒</small>
    </div>
{% endif %}
</body>
</html>
{% endif %}

bootleg/templates/bootleg/black_hole.html
{% extends bootleg_settings.BASE_TEMPLATE %}

bootleg/templates/bootleg/deploy_info.html
{% extends bootleg_settings.base_template %}
{% load static i18n %}
{% block content %}
{% include "bootleg/includes/deploy_info.html" %}
{% endblock %}

bootleg/templates/bootleg/detail_view.html
{% extends bootleg_settings.ADMIN_TEMPLATE %}
{% load i18n bootleg %}
{% block content %}

{% if request.is_ajax %}
    <p id="object_top_{{ object.id }}">
        <button type="button" class="btn btn-danger mt-4 element-remover" data-element-id="#object_view_{{ object.id}}">
            {% trans "Close" %}</button>
        </a>
    </p>
{% endif %}

<h1>{{ object }}</h1>
{% if not request.is_ajax %}
    <p>
        <button type="button" onclick="history.back()" class="btn btn-primary mt-4">{% trans "Go back" %}</button></a>
    </p>
{% endif %}

<div class="card mb-4 bg-light">
    <div class="card-body">
        {% for field in object.get_simple_fields_except_id %}
            {% if field.name != "name" %}
                <h4 class="mt-4">{{ field.verbose_name }}</h4>
                {% get_attribute object field.name %}
            {% endif %}
        {% endfor %}
        {% for many_to_one_field in object.get_many_to_one_fields %}
            <h4 class="mt-4">{{ many_to_one_field.verbose_name }}</h4>
            {{ many_to_one_field }}
        {% endfor %}
        {% render_many_to_one_objects object %}
        {% for image_field in object.get_image_fields %}
            <h4 class="mt-4">{{ image_field.verbose_name }}</h4>
            <img src="{% get_attribute object image_field.name %}" height="200" />
        {% endfor %}
        {% if not model.meta.disable_create_update is True %}
            <p>
                <a href="{{ object.get_update_url }}"><button type="button" class="btn btn-primary mt-4">{% trans "Update" %}</button></a>
            </p>
        {% endif %}
    </div>
</div>
{% endblock %}

bootleg/templates/bootleg/dev_null.html
{% extends bootleg_settings.BASE_TEMPLATE %}
{% load static i18n %}
{% block content %}
<pre>
In some operating systems, the null device is a device file that discards all data written to it but reports that the
write operation succeeded. This device is called /dev/null on Unix and Unix-like systems, NUL: or NUL on CP/M and DOS
(internally \DEV\NUL), nul on newer Windows systems[1] (internally \Device\Null on Windows NT),
NIL: on Amiga operating systems,[2] and NL: on OpenVMS.[3] In Windows Powershell, the equivalent is $null.[4]
It provides no data to any process that reads from it, yielding EOF immediately.[5] In IBM DOS/360, OS/360 (MFT, MVT),
OS/390 and z/OS operating systems, such files would be assigned in JCL to DD DUMMY.
</pre>
{% endblock %}

bootleg/templates/bootleg/list_view.html
{% extends bootleg_settings.ADMIN_TEMPLATE %}
{% load i18n static crispy_forms_tags humanize compress %}
{% load render_table from django_tables2 %}
{% block extra_head %}
    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static 'djangoql/css/completion.css' %}" />
    {% endcompress %}
{% endblock %}
{% block title %}{{ heading }}{% endblock title %}

{% block h1 %}{{ model.meta.verbose_name_plural }}{% endblock %}

{% block content %}
{{ model.class.get_extra_page_content }}

{% if filter_form %}
    <div class="row">
    {% if not model.meta.wide_table %}
            <div class="col-lg-2">
    {% endif %}
        {% if model.meta.wide_table %}
            <div class="col-lg-4">
        {% endif %}
                <div class="bg-light border rounded p-4">
                    {% if request.GET %}
                        <a href=".">
                            <button type="button" class="btn btn-sm btn-danger mb-2">{% trans "Clear search/sort filter" %}</button>
                        </a>
                    {% endif %}
                    {% crispy filter_form filter_form.helper %}
        {% if model.meta.wide_table %}
                </div>
            </div>
            <div class="col-lg-8">
                {% include "bootleg/includes/form.html" %}
            </div>
        {% endif %}
        </div>
    {% if not model.meta.wide_table %}
        </div>
        <div class="col-lg-10">
    {% endif %}
{% endif %}

{{ block.super }}
{% if not model.meta.disable_create_update is True %}
    <a href="{{ model.create_url }}">
        <button class="btn btn-primary mt-3 mb-3">{% trans "Create" %} {{ model.meta.verbose_name }}</button>
    </a>
{% endif %}

<div class="mt-4 mb-4">
    <strong id="model_count">{{ paginator.count|intcomma }}</strong> {{ model.meta.verbose_name_plural }} {% trans "found" %}
</div>

{% if object_list %}
    {% render_table table %}
{% endif %}
{% endblock content %}

{% if filter_form %}
    {% if not model.meta.wide_table %}
            </div>
        </div>
    {% endif %}
{% endif %}

{% block extra_body %}
    {% compress js %}
        <script src="{% static 'djangoql/js/lib/lexer.js' %}"></script>
        <script src="{% static 'djangoql/js/lib/LRUCache.js' %}"></script>
        <script src="{% static 'djangoql/js/completion.js' %}"></script>
        {% if not model_class.is_big_table %}
            <script>
            DjangoQL.DOMReady(function () {
                new DjangoQL({
                    introspections: {{ introspections|safe }},
                    selector: 'textarea[name=dql]',
                    syntaxHelp: null,
                    autoResize: false,
                    syntaxHelp: "{% url 'bootleg:djangoql_help' %}",
                });
            });
            </script>
        {% endif %}
    {% endcompress %}
{% endblock %}